spring.application.name=eCommerceApplication

# Server Configurations
server.port = 8080

# Logging Configurations
logging.level.root = INFO
logging.level.com.ecommerceapplication = DEBUG

# Show a nice banner on startup
spring.banner.location = classpath:banner.txt
